CREATE TABLE IF NOT EXISTS CPI_WikiDocs (
    ID VARCHAR(26) PRIMARY KEY,
    Name VARCHAR(1024) NOT NULL,
    Content TEXT NOT NULL,
    Description VARCHAR(4096) NOT NULL,
    Status VARCHAR(26) NOT NULL,
    OwnerUserID VARCHAR(26) NOT NULL,
    TeamID VARCHAR(26) NOT NULL,
    ChannelID VARCHAR(26) NOT NULL,
    CreateAt BIGINT NOT NULL,
    UpdateAt BIGINT NOT NULL DEFAULT 0,
    DeleteAt BIGINT NOT NULL DEFAULT 0,
    INDEX CPI_WikiDocs_TeamID (TeamID),
    INDEX CPI_WikiDocs_ChannelID (ChannelID)
) DEFAULT CHARACTER SET utf8mb4;
